jobs:
  - name: data-cleaning
    stages:
        - name: 'clean-base-tables'
          tasks:
            - name: 'google_search_data'
              params: {}
            - name: 'product_manufacturer_list'
              params: {}
            - name: 'sales_data'
              params: {}
            - name: 'social_media_data'
              params: {}
            - name: 'Theme_list'
              params: {}
            - name: 'Theme_product_list'
              params: {}
            
        - name: 'clean-derivative-tables'
          tasks:
            - name: 'sales'
              params: {}
        - name: 'train-test-split'
          tasks:
            - name: 'train-test'
              params:
                target: unit_price,
                test_size: 0.2
              
  - name: feat-engg
    stages:
        - name: 'feature-pipelines'
          tasks:
            - name: 'transform-features'
              params: 
                outliers: 
                  method: percentile
                  lb: 0.01
                  ub: 0.99
                  drop: True

  - name: model-gen
    stages:
        - name: 'model-creation'
          tasks:
            - name: 'train-model'
              params: {}

  - name: model-eval
    stages:
        - name: 'model-predict'
          tasks:
            - name: 'score-model'
              params: {}
